name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.environment[1] }}-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - [2.7, ubuntu]
          - [3.2, windows]
          - [3.3, ubuntu]
          - [3.4, ubuntu]
          - [3.5, ubuntu]
          - [3.6, ubuntu]
          - [3.7, ubuntu]
          - [3.8, ubuntu]
          - [3.9, ubuntu]
          - ['3.10.0-alpha - 3.10', ubuntu]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.environment[0] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.environment[0] }}

      - run: python test.py
