name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.environment[1] }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - [2.7, ubuntu-latest]
          - ['3.0', windows-latest]
          - [3.1, windows-latest]
          - [3.2, windows-latest]
          - [3.3, ubuntu-latest]
          - [3.4, ubuntu-latest]
          - [3.5, ubuntu-latest]
          - [3.6, ubuntu-latest]
          - [3.7, ubuntu-latest]
          - [3.8, ubuntu-latest]
          - [3.9, ubuntu-latest]
          - [3.10, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.environment[0] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.environment[0] }}

      - run: python test.py
